/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitcoinakka_Consensus__ */

#ifndef _Included_org_bitcoinakka_Consensus__
#define _Included_org_bitcoinakka_Consensus__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitcoinakka_Consensus__
 * Method:    verifyScript
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_org_bitcoinakka_Consensus_00024_verifyScript
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
